Portfolio
albertkantwi/MyPortfolio pull request #1
Opened 2023-04-28 08:30 UTC by albertkantwi

This is a simple Portfolio project. I humbly request for a review. Thank you.

2023-04-28 08:46 UTC, skyv26 reviewed
## Hi @albertkantwi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that linters errors. Kindly fixed them all and submit the project for review again from the dashboard.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-28 09:52 UTC, tugsem reviewed
## Invalid Code Review Request ❌ 

Hi @albertkantwi , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<h1>You have submitted a project, that doesn't have the right readme template</h2>
Here's  a reminder for you to keep in mind when filling out the template:

> README file should be descriptive:
> * All main headers from the [README template](https://github.com/microverseinc/readme-template) should be present  (**if any relevant header is missing, kindly mark the PR as invalid**)
>   * The only **optional** section is FAQ.
>   * Make sure to add the section **Future Features**, including 1-3 potential features to be added.
> * You should **remove the section description**, i.e. "> Describe the tech stack and include only the relevant sections that apply to your project." should be removed and filled in with your custom content.
> * You should remove **template logo**. Optionally, you can replace it with your own logo if you have one.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-28 11:12 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @albertkantwi , I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ] kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-04-28 11:12 UTC, MaganaAsiati commented on index.html
> +    </section>
- Kindly make sure that the container of the navigation barre section is in the `header` tag. :+1: 

* Typically the `header` tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info.The container of the section is a header tag.


- Kindly make sure the logo (if the design has one) has a link (`a` tag). :+1: 

   * This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.
   
- and also the hamburger button has a `nav` tag.

   * The `nav` tag is for semantics reasons and the right position for convention and user experience for mobile devices. The logo (if the design has one) is on the left and has a link (a tag).

```
eg.   
     
   <header class="container">
        <a href="#"> My Logo</a> 
            <nav class="button">
               <img src="button.png" alt="buttom" width="40px" height="40px"> 
            </nav>
    </header>

```

2023-04-28 11:12 UTC, MaganaAsiati commented on index.html
> +    </section>
- Kindly make sure that the list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag). :+1: 
   * Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href.

2023-04-28 11:12 UTC, MaganaAsiati commented on style.css
> +
- Kindly make sure that your background image is well  disposed and is not repeated to do that i can suggest you to add that property I listed below to this class :+1: 



```
.second-container {
  background-image: url(mobile-background.png);
  background-repeat: no-repeat;
  background-size: cover;
  min-height: calc(100vh - 599px);
  border-bottom-left-radius: 90px;
  background-color: #fff;
}
```

2023-04-28 14:06 UTC, Kamba56 requested changes
Hi @albertkantwi , 

Great work on making the changes requested by a previous reviewer 👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [x] Great job using flexbox to layout contents of your page !👏👏👏
- [x] 👏👏👏

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 14:06 UTC, Kamba56 commented on index.html
> +        <img src="twitter.png" alt="twitter" class="twitter" width="19.99px" height="19.99px">
- [ ] As suggested by the previous reviewer, kindly wrap all your social icons in an a tag. This is to improve user experience, when you add the link to your social as a href attribute, users can easily visit your social profile by clicking on the icon.

2023-04-28 14:06 UTC, Kamba56 commented on index.html
> +        <a href="#" class="logo">
- [ ] Great job wrapping the logo in an a tag. By default, a tags come with an underline but from the figma template, the logo isn't underlined. Kindly remove the underline on the logo.

2023-04-28 14:06 UTC, Kamba56 commented on index.html
> +    <header class="container">
- [Optional] Great job using a header element. I noticed that the spaces to the left and right of your header is more than that on the template. You are expected to stick to design guidelines as much as possible and this includes margins and paddings. Kindly fix this please.
- Figma
![Screenshot_2023-04-28-15-01-49-466_com android chrome~2](https://user-images.githubusercontent.com/94551484/235169576-73d9d537-7a10-4e2b-8784-6a3685e5e041.jpg)
- Your design 
![Screenshot_2023-04-28-14-56-57-442_com android chrome~2](https://user-images.githubusercontent.com/94551484/235169585-03bf47fb-488f-473e-a0a6-3aa0895fc345.jpg)

2023-04-28 16:13 UTC, ridwanediallo requested changes
# Changes Required ♻️
## Hi @albertkantwi , 


![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Your commit messages are descriptive. ✔


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 16:13 UTC, ridwanediallo commented on style.css
> +}
- [ ] Kindly as requested by the previous reviewer ensure that the logo is not underlined to make it similar to the template. :ok_hand: 

### Your logo 
![Screenshot from 2023-04-28 16-03-19](https://user-images.githubusercontent.com/89228743/235197638-cb5d6e76-4ce0-471b-aa1f-224c75a9f51d.png)


### Loog from the template
![Screenshot from 2023-04-28 16-03-08](https://user-images.githubusercontent.com/89228743/235197629-a45529d9-2951-45fb-9614-c8559f5769eb.png)

To remove the underline add `text-decoration: none;` to the `logo` class.
```suggestion
.logo {
  display: flex;
  order: 0;
  color: #6070ff;
  width: 76px;
  height: 20px;
  font-family: 'Poppins', sans-serif;
  font-style: normal;
  font-weight: 700;
  font-size: 18px;
  line-height: 20px;
  padding-right: 200px;
  flex-direction: row-reverse;
  text-decoration: none;
}
```

2023-04-28 16:13 UTC, ridwanediallo commented on style.css
> +}
- [ OPTIONAL ] Currently, the logo is not correctly aligned with the menu icon compared to the original design.

To fix that, you only need to add `align-items: center;` to the `container` class.
```suggestion
.container {
  display: flex;
  justify-content: space-around;
  align-items: center;
  width: 375px;
  height: 48 px;
}
```

2023-05-01 08:40 UTC, ichala approved these changes
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-01 08:49 UTC, merged